#!/usr/bin/env python3
"""
Exp. 2 — Compute macroscopic cluster entropy H_{p,τ}.

For each (pórtico p, time bucket τ) the script computes:

    share_{p,τ,k} = (Σ_{j∈(p,τ)} r_{j,k}) / N_{p,τ}
    H_{p,τ}       = -Σ_k share_{p,τ,k} · log(share_{p,τ,k})           (with 0·log0 = 0)

using **soft membership probabilities** r_{j,k} when available, falling back
to hard labels otherwise. The class label −1 (unassigned / low confidence) is
treated as a regular state "U" if config.entropy.include_unknown_class is true.

The script writes three parquet files, one per discretization (5/15/60 min).
A summary JSON captures means, percentiles, and per-year coverage.

This script depends on the dynamic_assignments DuckDB regenerated by
01_run_dynamic_gmm.py and on flujos.duckdb for the detection-level join.

Run example:
    python scripts/02_compute_entropy.py \
        --assignments-db results/dynamic_gmm/k5_2018-01-01_2024-09-30_assignments.duckdb \
        --flow-db Datos/flujos.duckdb \
        --output-15min results/entropy/k5_..._H_portico_15min.parquet \
        --output-5min  results/entropy/k5_..._H_portico_5min.parquet  \
        --output-60min results/entropy/k5_..._H_portico_60min.parquet \
        --output-summary results/entropy/k5_..._H_summary.json
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List

import duckdb
import numpy as np
import pandas as pd

THIS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = THIS_DIR.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.trc_paper.lib import (  # noqa: E402
    connect_duckdb_readonly,
    write_json_atomic,
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--assignments-db", required=True, type=Path)
    p.add_argument("--flow-db", required=True, type=Path)
    p.add_argument("--output-15min", required=True, type=Path)
    p.add_argument("--output-5min", required=True, type=Path)
    p.add_argument("--output-60min", required=True, type=Path)
    p.add_argument("--output-summary", required=True, type=Path)
    return p.parse_args()


def discover_probability_columns(
    con: duckdb.DuckDBPyConnection, table_qualified: str = "asgn_db.dynamic_assignments"
) -> List[str]:
    schema = con.execute(f"DESCRIBE {table_qualified}").fetchdf()
    return sorted(
        c for c in schema["column_name"].tolist()
        if c.startswith("cluster_prob_") and c[len("cluster_prob_"):].lstrip("-").isdigit()
    )


def compute_entropy_at_grain(
    assignments_db: Path,
    flow_db: Path,
    delta_minutes: int,
) -> pd.DataFrame:
    """Compute H_{p,τ} at the requested time discretization."""
    con = duckdb.connect(":memory:")
    con.execute(f"ATTACH '{assignments_db.as_posix()}' AS asgn_db (READ_ONLY)")
    con.execute(f"ATTACH '{flow_db.as_posix()}' AS flow_db (READ_ONLY)")

    prob_cols = discover_probability_columns(con, "asgn_db.dynamic_assignments")

    # Build soft membership SUM expressions. After SELECT a.* in the CTE the
    # columns are exposed unqualified, so reference them by bare name.
    if prob_cols:
        soft_sum_exprs = ", ".join(
            f"SUM(COALESCE({c}, 0.0)) AS sum_{c}" for c in prob_cols
        )
    else:
        soft_sum_exprs = ""

    # The query joins each detection to its most-recent causal assignment
    # via ASOF JOIN (same logic as src/clustering.py production path), buckets
    # by τ at the requested delta, and aggregates by (PORTICO, τ).
    query = f"""
        WITH detections AS (
            SELECT
                time_bucket(INTERVAL '{int(delta_minutes)} minutes', f.FECHA) AS tau,
                f.PORTICO AS portico,
                UPPER(TRIM(f.MATRICULA)) AS plate,
                f.FECHA AS detection_t
            FROM flow_db.flujos_duckdb AS f
            WHERE f.MATRICULA IS NOT NULL
              AND LENGTH(TRIM(f.MATRICULA)) BETWEEN 5 AND 6
        ),
        joined AS (
            SELECT d.tau, d.portico, d.plate, a.*
            FROM detections d
            ASOF LEFT JOIN asgn_db.dynamic_assignments a
              ON d.plate = a.plate
             AND d.detection_t >= a.window_end
        )
        SELECT
            portico,
            tau,
            COUNT(*) AS n_detections,
            COUNT(cluster_label) AS n_with_assignment,
            {soft_sum_exprs}{',' if soft_sum_exprs else ''}
            SUM(CASE WHEN cluster_label = -1 THEN 1 ELSE 0 END) AS n_unknown
        FROM joined
        GROUP BY 1, 2
        HAVING COUNT(*) >= 10
        ORDER BY 1, 2
    """
    t0 = time.time()
    df = con.execute(query).fetchdf()
    duration_s = time.time() - t0
    print(f"  Δ={delta_minutes}min: {len(df):,} rows, {duration_s:.1f}s")
    con.close()

    # Compute shares and entropy in pandas (fast, vectorized)
    share_cols = []
    if prob_cols:
        for c in prob_cols:
            share_col = c.replace("cluster_prob_", "share_")
            df[share_col] = df[f"sum_{c}"] / df["n_detections"].clip(lower=1)
            share_cols.append(share_col)
    # Add Unknown state if present
    df["share_U"] = df["n_unknown"] / df["n_detections"].clip(lower=1)
    share_cols.append("share_U")

    share_matrix = df[share_cols].to_numpy()
    # Numerical safety: clip very small probabilities to avoid log(0)
    p = np.clip(share_matrix, 1e-12, 1.0)
    df["H"] = -np.sum(p * np.log(p), axis=1)
    # Effective number of clusters
    df["n_eff"] = np.exp(df["H"])
    df["delta_minutes"] = int(delta_minutes)
    return df


def summarize(df_by_delta: Dict[int, pd.DataFrame]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for delta, df in df_by_delta.items():
        out[f"delta_{delta}min"] = {
            "n_buckets": int(len(df)),
            "H_mean": float(df["H"].mean()) if len(df) else float("nan"),
            "H_p05": float(df["H"].quantile(0.05)) if len(df) else float("nan"),
            "H_p50": float(df["H"].quantile(0.50)) if len(df) else float("nan"),
            "H_p95": float(df["H"].quantile(0.95)) if len(df) else float("nan"),
            "n_eff_mean": float(df["n_eff"].mean()) if len(df) else float("nan"),
            "n_porticos": int(df["portico"].nunique()) if len(df) else 0,
        }
    return out


def main() -> int:
    args = parse_args()
    args.output_15min.parent.mkdir(parents=True, exist_ok=True)
    print("=" * 60)
    print("Macroscopic cluster entropy H_{p,τ}")
    print("=" * 60)

    df_by_delta: Dict[int, pd.DataFrame] = {}
    for delta, outpath in (
        (5, args.output_5min),
        (15, args.output_15min),
        (60, args.output_60min),
    ):
        df = compute_entropy_at_grain(args.assignments_db, args.flow_db, delta)
        df.to_parquet(outpath, index=False)
        df_by_delta[delta] = df

    write_json_atomic(args.output_summary, summarize(df_by_delta))
    print(f"  summary JSON: {args.output_summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
