from __future__ import annotations

import glob
import os
from pathlib import Path
import math
from typing import List, Optional, Tuple

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from src import visualization as viz


try:
    import duckdb
except ImportError:
    duckdb = None

from src.config import RESULTADOS_DIR


def _list_duckdb_files(results_dir: Path) -> List[Path]:
    """Lists individual DuckDB files generated by Feature Engineering."""
    # Pattern: features_Flow_*.duckdb and features_Snapshot_*.duckdb
    # We can just glob features_*.duckdb and filter if needed, but user was specific.
    # Actually features_*.duckdb covers both.
    files = sorted(list(results_dir.glob("features_*.duckdb")), reverse=True)
    return files

def _get_db_metadata(file_path: Path) -> dict:
    """Retrieves metadata from DuckDB file without loading full data."""
    if not duckdb or not file_path.exists():
        return {}
    
    meta = {}
    try:
        con = duckdb.connect(str(file_path), read_only=True)
        
        # 1. Identify Table
        tables = [row[0] for row in con.execute("SELECT table_name FROM information_schema.tables").fetchall()]
        target_table = None
        stem = file_path.stem
        if stem in tables: target_table = stem
        elif tables:
            candidates = [t for t in tables if t.startswith("features_")]
            target_table = candidates[0] if candidates else tables[0]
            
        if not target_table:
            con.close()
            return {}
            
        meta["table_name"] = target_table
        
        # 2. Get Columns
        cols_info = con.execute(f"DESCRIBE {target_table}").fetchall()
        meta["columns"] = [c[0] for c in cols_info]
        
        # 3. Identify Portico Column
        portico_col = next((c for c in meta["columns"] if c in ["portico", "id_portico", "cod_portico"]), None)
        meta["portico_col"] = portico_col
        
        # 4. Get Time Range and Unique Porticos (Efficient Aggregation)
        # Check for timestamp column
        ts_col = "ts_min" if "ts_min" in meta["columns"] else "timestamp"
        
        if portico_col:
            # Get unique porticos
            p_res = con.execute(f"SELECT DISTINCT {portico_col} FROM {target_table} ORDER BY {portico_col}").fetchall()
            meta["porticos"] = [p[0] for p in p_res if p[0] is not None]
        
        # Get Time Range
        if ts_col in meta["columns"]:
             # If ts_min (int), convert to timestamp for min/max
             if ts_col == "ts_min":
                 # Min
                 min_val = con.execute(f"SELECT MIN({ts_col}) FROM {target_table}").fetchone()[0]
                 max_val = con.execute(f"SELECT MAX({ts_col}) FROM {target_table}").fetchone()[0]
                 if min_val is not None:
                     meta["min_time"] = pd.to_datetime(min_val, unit='m')
                     meta["max_time"] = pd.to_datetime(max_val, unit='m')
             else:
                 min_val = con.execute(f"SELECT MIN({ts_col}) FROM {target_table}").fetchone()[0]
                 max_val = con.execute(f"SELECT MAX({ts_col}) FROM {target_table}").fetchone()[0]
                 if min_val is not None:
                     meta["min_time"] = pd.to_datetime(min_val)
                     meta["max_time"] = pd.to_datetime(max_val)
        
        con.close()
    except Exception as e:
        st.error(f"Error extracting metadata from {file_path.name}: {e}")
        return {}
    
    return meta


def _load_data_slice(file_path: Path, table_name: str, 
                     start_time: pd.Timestamp, end_time: pd.Timestamp, 
                     selected_porticos: List[str], portico_col: str) -> Optional[pd.DataFrame]:
    if not duckdb: return None
    try:
        con = duckdb.connect(str(file_path), read_only=True)
        
        # Construct Query
        # Handle timestamp column name
        # We need to know if it is ts_min or timestamp in the DB
        cols = [c[0] for c in con.execute(f"DESCRIBE {table_name}").fetchall()]
        ts_col = "ts_min" if "ts_min" in cols else "timestamp"
        
        # Build SQL filter
        clauses = []
        
        # Time Filter
        if ts_col == "ts_min":
            # Convert timestamp to unix minute int
            t_start = int(start_time.timestamp() / 60)
            t_end = int(end_time.timestamp() / 60)
            clauses.append(f"{ts_col} >= {t_start}")
            clauses.append(f"{ts_col} <= {t_end}")
        else:
            clauses.append(f"{ts_col} >= '{start_time}'")
            clauses.append(f"{ts_col} <= '{end_time}'")
            
        # Portico Filter
        if selected_porticos and portico_col:
             # Ensure string conversion for join
             p_strs = [str(p) for p in selected_porticos]
             p_list = "', '".join(p_strs)
             clauses.append(f"{portico_col} IN ('{p_list}')")
        
        where_str = " AND ".join(clauses)
        if where_str:
            where_str = f"WHERE {where_str}"
            
        query = f"SELECT * FROM {table_name} {where_str}"
            
        df = con.execute(query).df()
        con.close()
        
        # Post-process timestamp
        if 'ts_min' in df.columns:
            df['timestamp'] = pd.to_datetime(df['ts_min'], unit='m')
        elif 'timestamp' in df.columns:
            df['timestamp'] = pd.to_datetime(df['timestamp'])
            
        return df
    except Exception as e:
        st.error(f"Error loading data slice: {e}")
        return None


def _list_feature_files(results_dir: Path) -> List[str]:
    all_feature_files = glob.glob(os.path.join(results_dir, "features_*.csv"))
    filtered = []
    for path in all_feature_files:
        name = os.path.basename(path)
        if "selected_names" in name:
            continue
        if "subset" in name:
            continue
        if not name.startswith("features_"):
            continue
        filtered.append(path)
    return sorted(filtered, key=os.path.basename, reverse=True)


def _render_controls(
    *,
    metadata: Optional[dict] = None, # Metadata driven
    df: Optional[pd.DataFrame] = None, # Legacy/CSV driven
    all_vars: List[str],
    portico_col_name: str,
    accident_df: pd.DataFrame,
) -> Tuple[
    List[str],
    List[str],
    Tuple[pd.Timestamp, pd.Timestamp],
    str,
    bool,
    Optional[str],
    Optional[str],
    Optional[str],
]:
    # Determine source of valid values
    if metadata:
         valid_porticos = sorted(metadata.get("porticos", []))
         min_time = metadata.get("min_time")
         max_time = metadata.get("max_time")
    elif df is not None:
         valid_porticos = sorted(df[portico_col_name].unique())
         min_time = df["timestamp"].min()
         max_time = df["timestamp"].max()
    else:
         return ([], [], (None, None), "Lineas", False, None, None, None)

    selected_variables = st.multiselect(
        "Variables a visualizar",
        all_vars,
        default=all_vars if all_vars else None,
        key="feature_explorer_vars",
    )
    
    selected_porticos = st.multiselect(
        "Porticos",
        valid_porticos,
        default=valid_porticos,
        key="feature_explorer_porticos",
    )
    
    # Ensure min/max are valid
    if pd.isna(min_time) or pd.isna(max_time):
         st.warning("No hay datos temporales válidos.")
         return (selected_variables, selected_porticos, (None, None), "Lineas", False, None, None, None)

    py_min_time = min_time.to_pydatetime()
    py_max_time = max_time.to_pydatetime()
    
    # Init with only 10% of data (approx)
    total_duration = py_max_time - py_min_time
    default_end = py_min_time + (total_duration * 0.1)
    if default_end > py_max_time: default_end = py_max_time
    
    # Render Slider
    start_time, end_time = st.slider(
        "Ventana temporal (Filtra la carga de datos)",
        min_value=py_min_time,
        max_value=py_max_time,
        value=(py_min_time, default_end),
        key="feature_explorer_time",
    )
    
    chart_type = st.selectbox(
        "Tipo de grafico",
        ["Lineas", "Dispersion", "Dispersion 3D", "Histograma", "Box Plot"],
        key="feature_explorer_chart",
    )

    x_var = y_var = z_var = None
    if chart_type == "Dispersion 3D":
        st.markdown("Ejes 3D")
        x_var = st.selectbox(
            "Eje X",
            all_vars,
            key="feature_explorer_x_var",
        )
        y_options = [v for v in all_vars if v != x_var] or all_vars
        y_var = st.selectbox(
            "Eje Y",
            y_options,
            key="feature_explorer_y_var",
        )
        z_options = [v for v in all_vars if v not in {x_var, y_var}] or all_vars
        z_var = st.selectbox(
            "Eje Z",
            z_options,
            key="feature_explorer_z_var",
        )

    normalize = st.checkbox(
        "Normalizar variables (Min-Max)",
        value=False,
        key="feature_explorer_normalize",
    )

    return (
        selected_variables,
        selected_porticos,
        (start_time, end_time),
        chart_type,
        normalize,
        x_var,
        y_var,
        z_var,
    )


def render_feature_explorer() -> None:
    st.subheader("Feature explorer")

    project_root = Path(__file__).resolve().parents[1]
    results_dir = project_root / "Resultados"
    data_dir = project_root / "Datos"

    # 1. DuckDB Files
    duck_files = _list_duckdb_files(results_dir)
    
    # 2. CSV Files (Legacy or external)
    feature_files = _list_feature_files(results_dir)
    
    if not duck_files and not feature_files:
        st.error(
            "No se encontraron archivos de features (`features_*.duckdb` o `features_*.csv`) en Resultados/."
        )
        return

    options = [{"type": "none", "name": None, "label": "Seleccione una fuente"}]
    
    for f in duck_files:
        options.append({"type": "duckdb", "name": f, "label": f"[DB]  {f.name}"})
        
    for f in feature_files:
        # csv paths are strings from _list_feature_files
        options.append({"type": "csv", "name": f, "label": f"[CSV] {os.path.basename(f)}"})
    
    selected_option = st.selectbox(
        "Fuente de features",
        options,
        format_func=lambda x: x["label"],
        key="feature_explorer_source",
        index=0,
    )

    if selected_option["type"] == "none":
        st.info("Seleccione una fuente para cargar features.")
        return


    portico_files = glob.glob(os.path.join(data_dir, "*orticos.csv"))
    if not portico_files:
        st.warning("No se encontraron archivos de porticos en Datos/.")
        return
    # Auto-select the first valid file
    selected_portico_file = sorted(portico_files, key=os.path.basename, reverse=True)[0]

    event_files = glob.glob(os.path.join(data_dir, "*ventos*.csv"))
    event_files.insert(0, "No mostrar accidentes")
    selected_event_file = st.selectbox(
        "Archivo de accidentes (opcional)",
        sorted(event_files, key=os.path.basename, reverse=True),
        format_func=lambda x: os.path.basename(x)
        if x != "No mostrar accidentes"
        else "No mostrar accidentes",
        key="feature_explorer_event_file",
    )

    meta = {}
    df = None
    
    # Logic Split: DuckDB vs CSV
    if selected_option["type"] == "duckdb":
        # 1. Get Metadata first for controls
        meta = _get_db_metadata(selected_option["name"])
        if not meta:
            st.error("No se pudo leer la metadata del archivo.")
            return

        portico_col_name = meta.get("portico_col")
        all_vars = sorted([c for c in meta.get("columns", []) if c not in [portico_col_name, "ts_min", "timestamp"]])
        
        # 2. Render Controls with Metadata
        # We need accident_df loaded to pass it (even if empty)
        # Porticos loaded?
        gantry_df = viz.load_gantry_data(selected_portico_file)
        if selected_event_file == "No mostrar accidentes":
             accident_df = pd.DataFrame()
        else:
             accident_df = viz.load_accident_data(selected_event_file, gantry_df)
        
        with st.expander("Filtros y visualizacion", expanded=True):
             (
                selected_vars, selected_ports, time_range,
                chart_type, normalize, x_var, y_var, z_var
             ) = _render_controls(
                metadata=meta,
                df=None, # Not loaded yet
                all_vars=all_vars,
                portico_col_name=portico_col_name,
                accident_df=accident_df
             )
        
        # 3. Load Data Slice based on filters
        start_t, end_t = time_range
        if start_t and end_t and selected_ports:
             with st.spinner("Cargando datos filtrados de la base de datos..."):
                 df = _load_data_slice(
                     selected_option["name"], 
                     meta["table_name"],
                     start_t, end_t,
                     selected_ports,
                     portico_col_name
                 )
             if df is not None and not df.empty:
                  # Verify effective load
                  st.success(f"Registros cargados: {len(df):,}")
    
    else:
        # Legacy CSV Flow
        df = viz.load_data(selected_option["name"])
        if df is None: return
        
        portico_col_name = next((c for c in ["portico", "id_portico"] if c in df.columns), None)
        all_vars = sorted([c for c in df.select_dtypes(include=["number"]).columns if c not in [portico_col_name, "ts_min"]])
        
        gantry_df = viz.load_gantry_data(selected_portico_file)
        if selected_event_file == "No mostrar accidentes":
             accident_df = pd.DataFrame()
        else:
             accident_df = viz.load_accident_data(selected_event_file, gantry_df)

        with st.expander("Filtros y visualizacion", expanded=True):
             (
                selected_vars, selected_ports, time_range,
                chart_type, normalize, x_var, y_var, z_var
             ) = _render_controls(
                metadata=None,
                df=df,
                all_vars=all_vars,
                portico_col_name=portico_col_name,
                accident_df=accident_df
             )
        
        start_t, end_t = time_range
        
    # Common Plotting Logic
    if df is None or df.empty:
        st.warning("No hay datos para mostrar (posiblemente por filtros muy restrictivos).")
        return
        
    # Assign back for consistency in variable names below
    selected_variables = selected_vars
    selected_porticos = selected_ports
    # start_time, end_time already unpacked
    start_time, end_time = time_range # ensure consistency
    required_vars = (
        selected_variables
        if chart_type != "Dispersion 3D"
        else [x_var, y_var, z_var]
    )
    if not required_vars or not selected_porticos:
        st.info("Seleccione variables y porticos para generar la grafica.")
        return

    start_time, end_time = time_range
    filtered_df = df[
        (df[portico_col_name].isin(selected_porticos))
        & (df["timestamp"] >= start_time)
        & (df["timestamp"] <= end_time)
    ]

    if filtered_df.empty:
        st.warning("No hay datos para los filtros seleccionados.")
        return

    df_to_plot = filtered_df.copy()
    vars_to_normalize = (
        selected_variables
        if chart_type != "Dispersion 3D"
        else [x_var, y_var, z_var]
    )
    if normalize and vars_to_normalize:
        for col in vars_to_normalize:
            min_val = df_to_plot[col].min()
            max_val = df_to_plot[col].max()
            if max_val > min_val:
                df_to_plot[col] = (df_to_plot[col] - min_val) / (
                    max_val - min_val
                )

    viz_map = {
        "Lineas": "Líneas",
        "Dispersion": "Dispersión (Scatter)",
        "Dispersion 3D": "Dispersión 3D",
    }
    viz_chart_type = viz_map.get(chart_type, chart_type)

    fig = viz.create_figure(
        df_to_plot,
        viz_chart_type,
        selected_variables
        if chart_type != "Dispersion 3D"
        else [x_var, y_var, z_var],
        portico_col_name,
    )

    if fig is None:
        st.warning("No se pudo generar la grafica.")
        return

    if not accident_df.empty and chart_type in ["Lineas", "Dispersion"]:
        accidents_in_view = accident_df[
            (accident_df["portico"].isin(selected_porticos))
            & (accident_df["timestamp"] >= start_time)
            & (accident_df["timestamp"] <= end_time)
        ]
        annotations = (
            list(fig.layout.annotations) if fig.layout.annotations else []
        )
        if not accidents_in_view.empty and selected_variables:
            y_col = selected_variables[0]
            for _, acc in accidents_in_view.iterrows():
                y_val = None
                rows = df_to_plot[df_to_plot[portico_col_name] == acc["portico"]]
                if not rows.empty:
                    y_val = pd.to_numeric(rows[y_col], errors="coerce").mean()
                if not pd.notna(y_val):
                    y_val = df_to_plot[y_col].mean()
                annotations.append(
                    dict(
                        x=acc["timestamp"],
                        y=y_val,
                        xref="x",
                        yref="y",
                        text="X",
                        showarrow=False,
                        font=dict(
                            family="sans serif",
                            size=16,
                            color="red",
                        ),
                        align="center",
                        bordercolor="white",
                        borderwidth=1,
                        bgcolor="rgba(255,255,255,0.5)",
                    )
                )
        if annotations:
            fig.update_layout(annotations=annotations)
    elif not accident_df.empty and chart_type == "Dispersion 3D":
        for tr in fig.data:
            try:
                tr.update(marker=dict(size=1, symbol="x"))
            except Exception:
                tr.update(marker=dict(size=3))

        accidents_in_view = accident_df[
            (accident_df["portico"].isin(selected_porticos))
            & (accident_df["timestamp"] >= start_time)
            & (accident_df["timestamp"] <= end_time)
        ]
        if not accidents_in_view.empty and x_var and y_var and z_var:
            xs, ys, zs, texts = [], [], [], []
            df_by_port = {
                p: g.sort_values("timestamp")
                for p, g in df_to_plot.groupby(portico_col_name)
            }
            for _, acc in accidents_in_view.iterrows():
                p = acc["portico"]
                sub = df_by_port.get(p)
                if sub is None or sub.empty:
                    continue
                try:
                    nearest_idx = (
                        sub["timestamp"] - acc["timestamp"]
                    ).abs().idxmin()
                    row = sub.loc[nearest_idx]
                except Exception:
                    sub_prior = sub[sub["timestamp"] <= acc["timestamp"]]
                    row = sub.iloc[-1] if sub_prior.empty else sub_prior.iloc[-1]
                xv = pd.to_numeric(row.get(x_var, None), errors="coerce")
                yv = pd.to_numeric(row.get(y_var, None), errors="coerce")
                zv = pd.to_numeric(row.get(z_var, None), errors="coerce")
                if pd.notna(xv) and pd.notna(yv) and pd.notna(zv):
                    xs.append(float(xv))
                    ys.append(float(yv))
                    zs.append(float(zv))
                    texts.append(f"{p}<br>{acc['timestamp']}")
            if xs:
                fig.add_trace(
                    go.Scatter3d(
                        x=xs,
                        y=ys,
                        z=zs,
                        mode="markers",
                        marker=dict(size=6, color="red"),
                        name="Accidentes",
                        text=texts,
                        hovertemplate="%{text}<extra></extra>",
                    )
                )

    st.plotly_chart(fig, width="stretch")
